version: '3.8'
services:
  vapa-servicedesk:
    build:
      context: .
      dockerfile: dockerfile
    image: vapa_servicedesk:latest
    container_name: vapa_servicedesk
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - /ruta/real/en/tu/nas/vapa_datos:/datos_persistentes
    working_dir: /app
    command: >
      sh -c "git pull &&
      ln -sf /datos_persistentes/gestion_incidencias_v3.db /app/gestion_incidencias_v3.db &&
      rm -rf /app/archivos_subidos &&
      ln -sfn /datos_persistentes /app/archivos_subidos &&
      streamlit run proyecto.py --server.port=8501 --server.address=0.0.0.0"
