server {
  listen 80;
  server_name servicedesk.vapa.es;
  location / { proxy_pass http://frontend:5173; proxy_set_header Host $host; }
  location /api/ { proxy_pass http://backend:8081/api/; proxy_set_header Host $host; }
}
